services:
  caddy:
    image: ghcr.io/nicjay/caddy-cloudflare-crowdsec:latest
    container_name: caddy
    user: ${PUID}:${PGID}
    environment:
      - ROOT_DOMAIN=${ROOT_DOMAIN}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - CROWDSEC_BOUNCER_KEY=${CROWDSEC_BOUNCER_KEY}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./config/caddy_data:/data/caddy
      - ./config/caddy_config:/config/caddy
      - ./logs:/var/log
    ports:
      - 443:443
      - 443:443/udp
    networks:
      - reverse-proxy
    restart: unless-stopped

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    security_opt:
      - no-new-privileges=true
    environment:
      - GID=${PGID}
      - TZ=${TZ}
      - COLLECTIONS=crowdsecurity/caddy crowdsecurity/whitelist-good-actors Dominic-Wagner/vaultwarden LePresidente/overseerr
      - CUSTOM_HOSTNAME=${ROOT_DOMAIN}
    volumes:
      - ./config/crowdsec_config:/etc/crowdsec
      - ./config/crowdsec_data:/var/lib/crowdsec/data
      - ../caddy/logs:/var/log/caddy:ro
      - ../vaultwarden/logs:/var/log/vaultwarden:ro
      - ../overseerr/logs:/var/log/overseerr:ro
    networks:
      - reverse-proxy
    restart: unless-stopped
    