services:
  caddy:
    image: caddy:latest
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
      - ./config:/config
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - proxy
    restart: unless-stopped