services:
  caddy:
    build: .
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data:/data
      - ./config:/config
    environment:
      - ROOT_DOMAIN
      - CLOUDFLARE_API_TOKEN
    ports:
      - 443:443
      - 443:443/udp
    networks:
      - proxy
    restart: unless-stopped