services:
  redbot:
    image: phasecorex/red-discordbot
    container_name: redbot
    environment:
      - PUID=${PGID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TOKEN=${TOKEN}
      - PREFIX=!
    volumes:
      - ./config:/data
    restart: unless-stopped