services:
  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:latest
    container_name: vaultwarden
    user: ${PUID}:${PGID}
    environment:
      - DOMAIN=${DOMAIN}
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=false
      - SHOW_PASSWORD_HINT=false
      - PUSH_ENABLED=true
      - PUSH_INSTALLATION_ID=${PUSH_INSTALLATION_ID}
      - PUSH_INSTALLATION_KEY=${PUSH_INSTALLATION_KEY}
    volumes:
      - ./config:/data
    networks:
      - reverse-proxy
    restart: unless-stopped
    