services:
  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:latest
    container_name: vaultwarden
    user: ${PUID}:${PGID}
    environment:
      - DOMAIN=${DOMAIN}
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=false
      - SHOW_PASSWORD_HINT=false
    volumes:
      - ./config:/data
    networks:
      - proxy
    restart: unless-stopped