networks:
  pterodactyl: {}

services:
  pterodactyl-panel:
    image: ghcr.io/pterodactyl/panel:latest
    container_name: pterodactyl-panel
    env_file:
      - panel.env
    environment:
      - APP_TIMEZONE=${TZ}
    volumes:
      - ./config/var:/app/var
      - ./config/nginx:/etc/nginx/http.d
      - ./config/logs:/app/storage/logs
    networks:
      - pterodactyl
      - proxy
    depends_on:
      - pterodactyl-database
      - pterodactyl-cache
    restart: unless-stopped

  pterodactyl-database:
    image: mariadb:10.11
    container_name: pterodactyl-database
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - database.env
    volumes:
      - ./config/database:/var/lib/mysql
    networks:
      - pterodactyl
    restart: unless-stopped

  pterodactyl-cache:
    image: redis:alpine
    container_name: pterodactyl-cache
    networks:
      - pterodactyl
    restart: unless-stopped
