services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    env_file:
      - homepage.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
    ports:
      - 3000:3000
    networks:
      - socket-proxy
    restart: unless-stopped
    