services:
  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: socket-proxy
    read_only: true
    tmpfs:
      - /run
    environment:
      - CONTAINERS=1
      - IMAGES=1
      - INFO=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket-proxy
    restart: unless-stopped
    