services:
  socket-proxy: # Access via port 2375
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: socket-proxy
    environment:
      - CONTAINERS=1
      - IMAGES=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket-proxy
    restart: unless-stopped