services:
  muse:
    image: ghcr.io/museofficial/muse:latest
    container_name: muse
    user: ${PUID}:${PGID}
    env_file:
      - muse.env
    volumes:
      - ./config:/data
    restart: unless-stopped
